project:
  type: website

website:
  title: "Statistics Foundations"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog_listing.qmd
        text: Blog
    right:
      - icon: git
        href: https://github.com/hello-data-science/hds_stats_foundations
        aria-label: github_gitlab
  repo-url: https://github.com/hello-data-science/hds_stats_foundations
  repo-actions: [edit, issue]
  repo-branch: main
  reader-mode: true

filters:
  - shinylive

format:
  html:
    mermaid:
      theme: default
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    code-fold: true
    code-link: true
    code-tools:
      source: repo
      toggle: true
      caption: Code

editor: source
