name: Deploy Quarto Website

permissions:
  contents: write
  pages: write

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: source

      - name: Set up Docker
        run: |
            docker pull rmgpanw/hds_stats_foundations:latest
            docker run --rm \
              -v ${{ github.workspace }}/source:/temp \
              rmgpanw/hds_stats_foundations:latest \
              bash -c ". venv/bin/activate && quarto render && cp -r docs /temp"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/source/docs
