name: Deploy Quarto Website

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        - name: Set up Docker
          run: |
            docker pull rmgpanw/hds_stats_foundations:latest
            docker run --rm rmgpanw/hds_stats_foundations:latest /bin/bash -c "
          . venv/bin/activate &&
          quarto render ./docs
            "

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
