name: Deploy Quarto Website

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      # Step 1: Set up Docker
      - name: Set up Docker
        run: |
          docker pull rmgpanw/hds_stats_foundations:latest
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace rmgpanw/hds_stats_foundations:latest /bin/bash -c "
            . venv/bin/activate &&
            quarto render
          "

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
